---
#
# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details.
#
version: 2.1
orbs:
  python: circleci/python@3.0.0
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10
    executor: python/default
    working_directory: ~/repo
    resource_class: small
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run setup
          command: python setup.py
workflows:
  build_and_deploy:
    jobs:
      - build_and_test
...

